name: fd_console
description: New version of Flutter's Debug Console, which provides testers with a view of the program's output logs outside of the IDE.
version: 0.0.1
homepage: https://github.com/zhoushuangjian001/flutter_console

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  
